os: linux
files:
  - source: /
    destination: /home/www/golang/src/github.com/dearing/havoc_server
hooks:
  BeforeInstall:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 600
      runas: havoc
