os: linux
files:
  - source: /
    destination: /home/www/golang/src/github.com/dearing/havoc_server
hooks:
  BeforeInstall:
    - location: scripts/install.sh
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: www
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: www
  ValidateService:
    - location: scripts/validate.sh
      timeout: 600
      runas: www
